name: Pull Request CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 40
    
    env:
      XC_VERSION: ${{ '13.1' }}
      XC_WORKSPACE: ${{ 'GithubActionSample.xcworkspace' }}
      XC_SCHEME: ${{ 'GithubActionSample' }}
      
      PROJECT_ROOT_PATH: ${{ 'GithubActionSample' }}
      
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

    - uses: actions/checkout@v2
    
    - name: Check dependency cache
      uses: actions/cache@v2
      id: cache_dependencies
      with:
        path: $PROJECT_ROOT_PATH/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: CocoaPod Install
      run: pod install --project-directory="$PROJECT_ROOT_PATH"/

    - name: Setup build for testing
      run: xcodebuild -scheme "$XC_SCHEME" -workspace "$PROJECT_ROOT_PATH/$XC_WORKSPACE" -destination 'platform=iOS Simulator,name=iPhone 8' build-for-testing | xcpretty --color
            
    - name: Run tests - iPhone 13
      run: xcodebuild -scheme "$XC_SCHEME" -workspace "$PROJECT_ROOT_PATH/$XC_WORKSPACE" -destination 'platform=iOS Simulator,name=iPhone 13' test-without-building | xcpretty --test --color
      
